services:
  frontend:
    image: ${FE_IMAGE:-ghcr.io/giangdq202/vmarble-warehouse-client:staging-latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
      - "10.8.0.1:3000:3000"
    logging:
      driver: "journald"
      options:
        tag: "vwms-staging-frontend"
    env_file:
      - .env.fe.staging
